translations = {
	tr: {
	'juz_anchor_label'       : 'Cüz ',
	'page_anchor_label'      : 's ',
	'bg_color_list_label'    : 'Zemin',
	'color_list_label'       : 'Renk',
	'font_family_list_label' : 'Font',
	'font_size_list_label'   : 'Punto',
	'goto_page_btn'          : 'Git',
	'juz_list_label'         : 'Cüz',
	'language_list_label'    : 'Dil',
	'page_input_label'       : 'Sayfa',
	'reset_btn'              : 'Reset',
	'sura_list_label'        : 'Sûre',
	'confirm_delete_bookmark': 'Yer işaretini silmek istiyor musunuz?',
	'page_info_page'         : 'syf',
	'page_info_juz'          : 'cz',
	'page_info_hizb'         : 'hzb',
	},

	en: {
	'juz_anchor_label'       : 'Juz ',
	'page_anchor_label'      : 'p ',
	'bg_color_list_label'    : 'Background',
	'color_list_label'       : 'Color',
	'font_family_list_label' : 'Font',
	'font_size_list_label'   : 'Font Size',
	'goto_page_btn'          : 'Go',
	'juz_list_label'         : 'Juz',
	'language_list_label'    : 'Language',
	'page_input_label'       : 'Page',
	'reset_btn'              : 'Reset',
	'sura_list_label'        : 'Surah',
	'confirm_delete_bookmark': 'Do you really want to delete bookmark?',
	'page_info_page'         : 'pg',
	'page_info_juz'          : 'jz',
	'page_info_hizb'         : 'hzb',
	}
};
